# Generated by Django 5.2.17 on 2026-09-29 10:06

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('border', '0002_massiv_globalid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuproqLugat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('mexanika', 'Mexanik tarkib'), ('shorlanish', "Sho'rlanish"), ('yuvilish', 'Yuvilish'), ('toshlanish', 'Toshloqlik'), ('klass', 'Klass')], max_length=16)),
                ('kod', models.IntegerField()),
                ('nom', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': "tuproq lug'ati",
                'ordering': ['tur', 'kod'],
                'constraints': [models.UniqueConstraint(fields=('tur', 'kod'), name='tuproqlugat_tur_kod_uniq')],
            },
        ),
        migrations.CreateModel(
            name='Tuproq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('globalid', models.CharField(max_length=64, unique=True)),
                ('bonitet', models.FloatField(blank=True, db_index=True, null=True)),
                ('maydon', models.FloatField(blank=True, null=True)),
                ('yer_osti_suvi', models.CharField(blank=True, default='', max_length=64)),
                ('yer_osti_suvi_min', models.FloatField(blank=True, null=True)),
                ('yer_osti_suvi_max', models.FloatField(blank=True, null=True)),
                ('massiv_nomi', models.CharField(blank=True, default='', max_length=255)),
                ('manba', models.JSONField(blank=True, default=dict)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('geom_mvt', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857)),
                ('tuman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuproqlar', to='border.tuman')),
                ('klass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='soil.tuproqlugat')),
                ('mexanika', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='soil.tuproqlugat')),
                ('shorlanish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='soil.tuproqlugat')),
                ('toshlanish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='soil.tuproqlugat')),
                ('yuvilish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='soil.tuproqlugat')),
            ],
            options={
                'verbose_name_plural': 'tuproqlar',
            },
        ),
    ]
