# Generated by Django 5.2.17 on 2026-09-29 11:49

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('border', '0003_massiv_kalitsiz'),
        ('soil', '0001_boshlangich'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agrokimyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korsatkich', models.CharField(choices=[('kaliy', 'Kaliy'), ('fosfor', 'Fosfor'), ('gumus', 'Gumus')], db_index=True, max_length=16)),
                ('yil', models.IntegerField(blank=True, db_index=True, null=True)),
                ('daraja', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('daraja_nom', models.CharField(blank=True, default='', max_length=32)),
                ('gradatsiya', models.CharField(blank=True, default='', max_length=32)),
                ('maydon', models.FloatField(blank=True, null=True)),
                ('manba', models.JSONField(blank=True, default=dict)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('geom_mvt', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857)),
                ('tuman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agrokimyolar', to='border.tuman')),
            ],
            options={
                'verbose_name_plural': 'agrokimyolar',
                'indexes': [models.Index(fields=['korsatkich', 'yil'], name='agrokimyo_kors_yil_idx')],
            },
        ),
    ]
