# Generated by Django 5.2.17 on 2026-09-30 05:40

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


KO_CHIRISH = [
    "INSERT INTO soil_kaliy (yil, daraja, daraja_nom, gradatsiya, tuman_id, maydon, manba, geom, geom_mvt) SELECT yil, daraja, daraja_nom, gradatsiya, tuman_id, maydon, manba, geom, geom_mvt FROM soil_agrokimyo WHERE korsatkich = 'kaliy' ORDER BY id",
    "INSERT INTO soil_fosfor (yil, daraja, daraja_nom, gradatsiya, tuman_id, maydon, manba, geom, geom_mvt) SELECT yil, daraja, daraja_nom, gradatsiya, tuman_id, maydon, manba, geom, geom_mvt FROM soil_agrokimyo WHERE korsatkich = 'fosfor' ORDER BY id",
    "INSERT INTO soil_gumus (yil, daraja, daraja_nom, gradatsiya, tuman_id, maydon, manba, geom, geom_mvt) SELECT yil, daraja, daraja_nom, gradatsiya, tuman_id, maydon, manba, geom, geom_mvt FROM soil_agrokimyo WHERE korsatkich = 'gumus' ORDER BY id",
]

QAYTARISH = [
    "INSERT INTO soil_agrokimyo (korsatkich, yil, daraja, daraja_nom, gradatsiya, tuman_id, maydon, manba, geom, geom_mvt) SELECT 'kaliy', yil, daraja, daraja_nom, gradatsiya, tuman_id, maydon, manba, geom, geom_mvt FROM soil_kaliy ORDER BY id",
    "INSERT INTO soil_agrokimyo (korsatkich, yil, daraja, daraja_nom, gradatsiya, tuman_id, maydon, manba, geom, geom_mvt) SELECT 'fosfor', yil, daraja, daraja_nom, gradatsiya, tuman_id, maydon, manba, geom, geom_mvt FROM soil_fosfor ORDER BY id",
    "INSERT INTO soil_agrokimyo (korsatkich, yil, daraja, daraja_nom, gradatsiya, tuman_id, maydon, manba, geom, geom_mvt) SELECT 'gumus', yil, daraja, daraja_nom, gradatsiya, tuman_id, maydon, manba, geom, geom_mvt FROM soil_gumus ORDER BY id",
]


class Migration(migrations.Migration):

    dependencies = [
        ('border', '0003_massiv_kalitsiz'),
        ('soil', '0002_agrokimyo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fosfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.IntegerField(blank=True, db_index=True, null=True)),
                ('daraja', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('daraja_nom', models.CharField(blank=True, default='', max_length=32)),
                ('gradatsiya', models.CharField(blank=True, default='', max_length=32)),
                ('maydon', models.FloatField(blank=True, null=True)),
                ('manba', models.JSONField(blank=True, default=dict)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('geom_mvt', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857)),
                ('tuman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='border.tuman')),
            ],
            options={
                'verbose_name_plural': 'fosfor',
            },
        ),
        migrations.CreateModel(
            name='Gumus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.IntegerField(blank=True, db_index=True, null=True)),
                ('daraja', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('daraja_nom', models.CharField(blank=True, default='', max_length=32)),
                ('gradatsiya', models.CharField(blank=True, default='', max_length=32)),
                ('maydon', models.FloatField(blank=True, null=True)),
                ('manba', models.JSONField(blank=True, default=dict)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('geom_mvt', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857)),
                ('tuman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='border.tuman')),
            ],
            options={
                'verbose_name_plural': 'gumus',
            },
        ),
        migrations.CreateModel(
            name='Kaliy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.IntegerField(blank=True, db_index=True, null=True)),
                ('daraja', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('daraja_nom', models.CharField(blank=True, default='', max_length=32)),
                ('gradatsiya', models.CharField(blank=True, default='', max_length=32)),
                ('maydon', models.FloatField(blank=True, null=True)),
                ('manba', models.JSONField(blank=True, default=dict)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('geom_mvt', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857)),
                ('tuman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='border.tuman')),
            ],
            options={
                'verbose_name_plural': 'kaliy',
            },
        ),
        migrations.RunSQL(KO_CHIRISH, QAYTARISH),
        migrations.DeleteModel(
            name='Agrokimyo',
        ),
    ]
