# Generated by Django 5.2.17 on 2026-09-29 08:48

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('border', '0002_massiv_globalid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manba_fid', models.BigIntegerField(unique=True)),
                ('kontur_raqami', models.IntegerField(blank=True, null=True)),
                ('yagona_kontur', models.CharField(blank=True, max_length=64, null=True)),
                ('eski_kontur', models.CharField(blank=True, max_length=64, null=True)),
                ('umumiy_maydoni', models.FloatField(blank=True, null=True)),
                ('mfy', models.CharField(blank=True, max_length=255, null=True)),
                ('massiv', models.CharField(blank=True, max_length=255, null=True)),
                ('satr', models.CharField(blank=True, max_length=255, null=True)),
                ('izox', models.TextField(blank=True, null=True)),
                ('haydalma_yer_sug', models.FloatField(blank=True, null=True)),
                ('haydalma_shartli_sug', models.FloatField(blank=True, null=True)),
                ('haydalma_lalmi', models.FloatField(blank=True, null=True)),
                ('dehqon_xuj_sug', models.FloatField(blank=True, null=True)),
                ('dehqon_xuj_lalmi', models.FloatField(blank=True, null=True)),
                ('issiqxona', models.FloatField(blank=True, null=True)),
                ('boglar_sug', models.FloatField(blank=True, null=True)),
                ('bog_shartli_sug', models.FloatField(blank=True, null=True)),
                ('bog_lalmi', models.FloatField(blank=True, null=True)),
                ('bog_intensiv', models.FloatField(blank=True, null=True)),
                ('uzumzor_sug', models.FloatField(blank=True, null=True)),
                ('uzumzor_shartli_sug', models.FloatField(blank=True, null=True)),
                ('uzumzor_lalmi', models.FloatField(blank=True, null=True)),
                ('uzumzor_intensiv', models.FloatField(blank=True, null=True)),
                ('kuchatxona', models.FloatField(blank=True, null=True)),
                ('tutzor', models.FloatField(blank=True, null=True)),
                ('terakzor', models.FloatField(blank=True, null=True)),
                ('buz_yer_sug', models.FloatField(blank=True, null=True)),
                ('buz_yer_lalmi', models.FloatField(blank=True, null=True)),
                ('pichanzor', models.FloatField(blank=True, null=True)),
                ('utloq_yaylov', models.FloatField(blank=True, null=True)),
                ('utloq_yaylov_suvli', models.FloatField(blank=True, null=True)),
                ('jami_qx_yeri', models.FloatField(blank=True, null=True)),
                ('jami_qx_sug_yeri', models.FloatField(blank=True, null=True)),
                ('tomarqa', models.FloatField(blank=True, null=True)),
                ('dala_tomorqa', models.FloatField(blank=True, null=True)),
                ('meliorativ_hol_yer', models.FloatField(blank=True, null=True)),
                ('urmonzor', models.FloatField(blank=True, null=True)),
                ('butazor', models.FloatField(blank=True, null=True)),
                ('daraxtzor_jar_daryo_buyi', models.FloatField(blank=True, null=True)),
                ('lhota_daraxtzor', models.FloatField(blank=True, null=True)),
                ('urmon_kuchatxona', models.FloatField(blank=True, null=True)),
                ('ariq_kanal_zovur', models.FloatField(blank=True, null=True)),
                ('kol', models.FloatField(blank=True, null=True)),
                ('suv_ombor_havza', models.FloatField(blank=True, null=True)),
                ('dengiz_daryo_soy', models.FloatField(blank=True, null=True)),
                ('botqoqliklar', models.FloatField(blank=True, null=True)),
                ('qurilish_osti_yeri', models.FloatField(blank=True, null=True)),
                ('yollar', models.FloatField(blank=True, null=True)),
                ('kuchalar_maydon', models.FloatField(blank=True, null=True)),
                ('shurxok_yer', models.FloatField(blank=True, null=True)),
                ('qumlar', models.FloatField(blank=True, null=True)),
                ('boshqa_yer', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('geom_mvt', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857)),
                ('tuman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='konturlar', to='border.tuman')),
            ],
            options={
                'verbose_name_plural': 'konturlar',
                'indexes': [models.Index(fields=['tuman', 'kontur_raqami'], name='kontur_tuman_raqam_idx')],
            },
        ),
    ]
