# Generated by Django 5.2.17 on 2026-09-29 09:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0001_boshlangich'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontur',
            name='geom_mvt_s',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, spatial_index=False, srid=3857),
        ),
        migrations.AddField(
            model_name='kontur',
            name='maydon_mvt',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
