# Generated by Django 5.2.17 on 2026-09-29 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('border', '0002_massiv_globalid'),
        ('land', '0002_geom_mvt_s_maydon_mvt'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontur',
            name='tuman_geo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geo_konturlar', to='border.tuman'),
        ),
        migrations.AddField(
            model_name='kontur',
            name='tur',
            field=models.CharField(choices=[('sugoriladigan', "Sug'oriladigan"), ('aniqlanmagan', 'Aniqlanmagan')], db_index=True, default='aniqlanmagan', max_length=32),
        ),
    ]
