# Generated by Django 5.2.17 on 2026-09-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0003_kontur_tuman_geo_tur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontur',
            name='tur',
            field=models.CharField(choices=[('sugoriladigan', "Sug'oriladigan"), ('qx_tuproq', "QX yeri (tuproq bo'yicha)"), ('aniqlanmagan', 'Aniqlanmagan')], db_index=True, default='aniqlanmagan', max_length=32),
        ),
    ]
