# Generated by Django 5.2.17 on 2026-09-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0004_tur_qx_tuproq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontur',
            name='tur',
            field=models.CharField(choices=[('sugoriladigan', "Sug'oriladigan"), ('aniqlanmagan', 'Aniqlanmagan')], db_index=True, default='aniqlanmagan', max_length=32),
        ),
    ]
