# Generated by Django 5.2.17 on 2026-09-30 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0005_tur_qx_tuproq_olib_tashlash'),
    ]

    operations = [
        migrations.CreateModel(
            name='KonturKorsatkich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonitet', models.FloatField(blank=True, null=True)),
                ('shorlanish', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gumus', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fosfor', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('kaliy', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('kontur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='korsatkich', to='land.kontur')),
            ],
            options={
                'verbose_name_plural': "kontur ko'rsatkichlari",
            },
        ),
    ]
