"""Kontur yer turi ustunlari: (ustun, o'qiladigan nom, jami belgisi)."""

YER_TURLARI = [
    ("haydalma_yer_sug", "Haydalma (sug'oriladigan)", False),
    ("haydalma_shartli_sug", "Haydalma (shartli sug'oriladigan)", False),
    ("haydalma_lalmi", "Haydalma (lalmi)", False),
    ("dehqon_xuj_sug", "Dehqon xo'jaligi (sug'oriladigan)", False),
    ("dehqon_xuj_lalmi", "Dehqon xo'jaligi (lalmi)", False),
    ("issiqxona", "Issiqxona", False),
    ("boglar_sug", "Bog'lar (sug'oriladigan)", False),
    ("bog_shartli_sug", "Bog'lar (shartli sug'oriladigan)", False),
    ("bog_lalmi", "Bog'lar (lalmi)", False),
    ("bog_intensiv", "Bog'lar (intensiv)", False),
    ("uzumzor_sug", "Uzumzor (sug'oriladigan)", False),
    ("uzumzor_shartli_sug", "Uzumzor (shartli sug'oriladigan)", False),
    ("uzumzor_lalmi", "Uzumzor (lalmi)", False),
    ("uzumzor_intensiv", "Uzumzor (intensiv)", False),
    ("kuchatxona", "Ko'chatxona", False),
    ("tutzor", "Tutzor", False),
    ("terakzor", "Terakzor", False),
    ("buz_yer_sug", "Bo'z yer (sug'oriladigan)", False),
    ("buz_yer_lalmi", "Bo'z yer (lalmi)", False),
    ("pichanzor", "Pichanzor", False),
    ("utloq_yaylov", "O'tloq va yaylov", False),
    ("utloq_yaylov_suvli", "O'tloq va yaylov (suvli)", False),
    ("jami_qx_yeri", "Jami QX yeri", True),
    ("jami_qx_sug_yeri", "Jami QX sug'oriladigan yeri", True),
    ("tomarqa", "Tomorqa", False),
    ("dala_tomorqa", "Dala tomorqasi", False),
    ("meliorativ_hol_yer", "Meliorativ holati yomon yer", False),
    ("urmonzor", "O'rmonzor", False),
    ("butazor", "Butazor", False),
    ("daraxtzor_jar_daryo_buyi", "Daraxtzor (jar, daryo bo'yi)", False),
    ("lhota_daraxtzor", "Lhota daraxtzor", False),
    ("urmon_kuchatxona", "O'rmon ko'chatxonasi", False),
    ("ariq_kanal_zovur", "Ariq, kanal, zovur", False),
    ("kol", "Ko'l", False),
    ("suv_ombor_havza", "Suv ombori va havza", False),
    ("dengiz_daryo_soy", "Dengiz, daryo, soy", False),
    ("botqoqliklar", "Botqoqliklar", False),
    ("qurilish_osti_yeri", "Qurilish osti yeri", False),
    ("yollar", "Yo'llar", False),
    ("kuchalar_maydon", "Ko'chalar", False),
    ("shurxok_yer", "Sho'rxok yer", False),
    ("qumlar", "Qumlar", False),
    ("boshqa_yer", "Boshqa yer", False),
]

USTUNLAR = [u[0] for u in YER_TURLARI]
