# Generated by Django 5.2.17 on 2026-09-29 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('land', '0005_tur_qx_tuproq_olib_tashlash'),
    ]

    operations = [
        migrations.CreateModel(
            name='KonturRelyef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balandlik_min', models.FloatField(blank=True, null=True)),
                ('balandlik_ortacha', models.FloatField(blank=True, null=True)),
                ('balandlik_max', models.FloatField(blank=True, null=True)),
                ('qiyalik_ortacha', models.FloatField(blank=True, null=True)),
                ('qiyalik_sinfi', models.CharField(blank=True, choices=[('tekis', 'Tekis (<1°)'), ('yengil', 'Yengil (1-3°)'), ('orta', "O'rta (3-7°)"), ('tik', 'Tik (>7°)')], max_length=16, null=True)),
                ('yonalish', models.CharField(blank=True, choices=[('Sh', 'Shimol'), ('ShSh', 'Shimoli-sharq'), ('Sq', 'Sharq'), ('JSq', 'Janubi-sharq'), ('J', 'Janub'), ('JG', "Janubi-g'arb"), ('G', "G'arb"), ('ShG', "Shimoli-g'arb")], max_length=4, null=True)),
                ('yonalish_gradus', models.FloatField(blank=True, null=True)),
                ('hisoblangan', models.DateTimeField(auto_now=True)),
                ('kontur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relyef', to='land.kontur')),
            ],
            options={
                'verbose_name_plural': 'kontur relyeflari',
            },
        ),
    ]
