# Generated by Django 5.2.17 on 2026-09-29 11:52

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('border', '0003_massiv_kalitsiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='IqlimKatak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=16, unique=True)),
                ('ix', models.IntegerField()),
                ('iy', models.IntegerField()),
                ('markaz_lon', models.FloatField()),
                ('markaz_lat', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('geom_mvt', django.contrib.gis.db.models.fields.PolygonField(srid=3857)),
                ('sugorilad_maydon', models.FloatField(default=0)),
                ('tuman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iqlim_kataklari', to='border.tuman')),
            ],
            options={
                'verbose_name_plural': 'iqlim kataklari',
            },
        ),
        migrations.CreateModel(
            name='IqlimKunlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('t_min', models.FloatField(blank=True, null=True)),
                ('t_max', models.FloatField(blank=True, null=True)),
                ('t_ort', models.FloatField(blank=True, null=True)),
                ('yogin', models.FloatField(blank=True, null=True)),
                ('et0', models.FloatField(blank=True, null=True)),
                ('radiatsiya', models.FloatField(blank=True, null=True)),
                ('shamol', models.FloatField(blank=True, null=True)),
                ('namlik', models.FloatField(blank=True, null=True)),
                ('katak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kunlik', to='climate.iqlimkatak')),
            ],
            options={
                'verbose_name_plural': 'iqlim kunlik',
            },
        ),
        migrations.CreateModel(
            name='IqlimOylik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.SmallIntegerField()),
                ('oy', models.SmallIntegerField()),
                ('t_min', models.FloatField(blank=True, null=True)),
                ('t_max', models.FloatField(blank=True, null=True)),
                ('t_ort', models.FloatField(blank=True, null=True)),
                ('yogin', models.FloatField(blank=True, null=True)),
                ('et0', models.FloatField(blank=True, null=True)),
                ('radiatsiya', models.FloatField(blank=True, null=True)),
                ('shamol', models.FloatField(blank=True, null=True)),
                ('namlik', models.FloatField(blank=True, null=True)),
                ('kunlar', models.SmallIntegerField(default=0)),
                ('katak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oylik', to='climate.iqlimkatak')),
            ],
            options={
                'verbose_name_plural': 'iqlim oylik',
            },
        ),
        migrations.CreateModel(
            name='IqlimYillik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.SmallIntegerField()),
                ('fah', models.FloatField(blank=True, null=True)),
                ('sovuqsiz_kunlar', models.SmallIntegerField(blank=True, null=True)),
                ('oxirgi_bahorgi_sovuq', models.DateField(blank=True, null=True)),
                ('birinchi_kuzgi_sovuq', models.DateField(blank=True, null=True)),
                ('yogin', models.FloatField(blank=True, null=True)),
                ('et0', models.FloatField(blank=True, null=True)),
                ('t_ort', models.FloatField(blank=True, null=True)),
                ('katak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yillik', to='climate.iqlimkatak')),
            ],
            options={
                'verbose_name_plural': 'iqlim yillik',
            },
        ),
        migrations.AddConstraint(
            model_name='iqlimkatak',
            constraint=models.UniqueConstraint(fields=('ix', 'iy'), name='iqlimkatak_ix_iy_uniq'),
        ),
        migrations.AddIndex(
            model_name='iqlimkunlik',
            index=models.Index(fields=['sana'], name='iqlimkunlik_sana_idx'),
        ),
        migrations.AddConstraint(
            model_name='iqlimkunlik',
            constraint=models.UniqueConstraint(fields=('katak', 'sana'), name='iqlimkunlik_katak_sana_uniq'),
        ),
        migrations.AddConstraint(
            model_name='iqlimoylik',
            constraint=models.UniqueConstraint(fields=('katak', 'yil', 'oy'), name='iqlimoylik_katak_yil_oy_uniq'),
        ),
        migrations.AddConstraint(
            model_name='iqlimyillik',
            constraint=models.UniqueConstraint(fields=('katak', 'yil'), name='iqlimyillik_katak_yil_uniq'),
        ),
    ]
