# Generated by Django 5.2.17 on 2026-09-29 08:27

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('geom_mvt', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857)),
                ('geom_mvt_s', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857)),
                ('bbox', models.JSONField(default=list)),
                ('kod', models.PositiveIntegerField(unique=True)),
                ('soato', models.CharField(max_length=16, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('tip', models.CharField(choices=[('tuman', 'Tuman'), ('shahar', 'Shahar')], default='tuman', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'tumanlar',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Viloyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('geom_mvt', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857)),
                ('geom_mvt_s', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857)),
                ('bbox', models.JSONField(default=list)),
                ('region_id', models.PositiveSmallIntegerField(unique=True)),
                ('soato', models.CharField(max_length=16, unique=True)),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'viloyatlar',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Massiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('geom_mvt', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857)),
                ('geom_mvt_s', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857)),
                ('bbox', models.JSONField(default=list)),
                ('massiv_id', models.BigIntegerField(unique=True)),
                ('nom', models.CharField(blank=True, max_length=150)),
                ('tuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='massivlar', to='border.tuman')),
            ],
            options={
                'verbose_name_plural': 'massivlar',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='tuman',
            name='viloyat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tumanlar', to='border.viloyat'),
        ),
    ]
