# Generated by Django 5.2.17 on 2026-09-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('border', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='massiv',
            name='globalid',
            field=models.CharField(default='', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='massiv',
            name='massiv_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
