# Generated by Django 5.2.17 on 2026-09-29 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('border', '0002_massiv_globalid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massiv',
            name='globalid',
        ),
        migrations.RemoveField(
            model_name='massiv',
            name='massiv_id',
        ),
    ]
