# Generated by Django 5.2.17 on 2026-09-30 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('land', '0006_kontur_korsatkich'),
    ]

    operations = [
        migrations.CreateModel(
            name='EkinClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.IntegerField(unique=True)),
                ('nom', models.CharField(max_length=128)),
                ('guruh', models.CharField(choices=[('paxta', 'Paxta'), ('galla', 'Don (g‘alla, arpa, javdar, suli)'), ('sholi', 'Sholi'), ('makkajoxori', 'Makkajo‘xori (don)'), ('moyli', 'Moyli ekinlar'), ('sabzavot', 'Sabzavot'), ('poliz', 'Poliz'), ('dukkakli', 'Dukkakli ekinlar'), ('kartoshka', 'Kartoshka'), ('ozuqa', 'Ozuqa ekinlari'), ('bog', 'Bog‘ va mevali daraxtlar'), ('uzum', 'Uzumzor'), ('boshqa', 'Boshqa (texnik, dorivor va h.k.)')], db_index=True, max_length=16)),
            ],
            options={
                'verbose_name_plural': 'ekin klasslari',
                'ordering': ['kod'],
            },
        ),
        migrations.CreateModel(
            name='KonturEkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.PositiveSmallIntegerField()),
                ('maydon', models.FloatField()),
                ('ulush', models.FloatField()),
                ('asosiy', models.BooleanField(default=False)),
                ('ekin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kontur_ekinlar', to='crop.ekinclass')),
                ('kontur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ekinlar', to='land.kontur')),
            ],
            options={
                'verbose_name_plural': 'kontur ekinlari',
                'indexes': [models.Index(fields=['kontur', 'yil'], name='konturekin_kontur_yil_idx'), models.Index(fields=['yil', 'ekin'], name='konturekin_yil_ekin_idx')],
                'constraints': [models.UniqueConstraint(fields=('kontur', 'yil', 'ekin'), name='konturekin_kontur_yil_ekin_uniq'), models.UniqueConstraint(condition=models.Q(('asosiy', True)), fields=('kontur', 'yil'), name='konturekin_asosiy_uniq')],
            },
        ),
    ]
