# Generated by Django 5.2.17 on 2026-09-30 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0001_boshlangich'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ekinclass',
            name='guruh',
        ),
    ]
